export const ADD_FAVORITE = 'ADD_FAVORITE';
export const ADD_FRIEND = 'ADD_FRIEND';
export const SEARCH_LOCATION = 'SEARCH_LOCATION';
export const STORE_USERINFO = 'STORE_USERINFO';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';